version: '2'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - './mongodb-data:/data/db'
  
  redis:
    image: 'redis:alpine'
    #volumes:
    #  - './redis-data:/data'
    ports:
      - '6379:6379'
  
  b2c-admin:
    image: b2c-admin

  b2c-api:
    image: b2c-api
    links:
      - mongodb
      - redis
  nginx:
      image: linuxserver/letsencrypt
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /opt/appdata/letsencrypt/config:/config
        - ./nginx.conf:/config/nginx/site-confs/default
      depends_on:
        - b2c-admin
        - b2c-api
      container_name: nginx
      environment:
        - PUID=497 # get on dockerhost through command "id <user>""
        - PGID=497
        - EMAIL=alexandredias1995@gmail.com
        - URL=b2c-app.info
        - SUBDOMAINS=www
        - TZ=America/NewYork
        - VALIDATION=http
