version: '2'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - './mongodb-data:/data/db'
  
  redis:
    image: 'redis:alpine'
    volumes:
      - './redis-data:/data'
    ports:
      - '6379:6379'
  
  b2c-admin:
    image: b2c-admin

  b2c-api:
    image: b2c-api
    links:
      - mongodb
      - redis
  proxy:
    image: proxy
    ports:
      - '80:80'
    restart: always
